### ISSUE TITLE
Ideas from TODO.txt

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/stonesense#44]
- [ ] Add the ability to handle color patterns on creatures.
- [ ] Add the ability to distinguish which hand/foot equipment is equipped on.  
- [ ] Add the allegro shader module and figure out ways to take advantage of it (fog? weather? dynamic lighting?).
- [ ] Figure out a way to use sockets to make our own cache of the map?
- [ ] Make some DFHack tools available through the Stonesense interface (probe? prospector?)

Posted here as part of documentation cleanup.
